### ISSUE TITLE
Fails in browser with error "idpiframe_initialization_failed"  if 3rd party cookies are not enabled in Chrome browser

### ISSUE THREAD

**Issue by ghost** [gsuitedevs/browser-samples#10]
Fix is to change the flag for 3rd party cookies in Chrome settings.
May be worth adding to instructions/ troubleshooting. Adding info here in case others encounter the same pitfall.

**Comment by erickoledadevrel** [comment]
Thanks for bringing this to our attention. I'll work on expanding the "Troubleshooting" section on the quickstart instructions to mention this requirement.

**Comment by erickoledadevrel** [comment]
I've added a section to the Troubleshooting section of the guide that covers this scenario:

https://developers.google.com/calendar/quickstart/js#troubleshooting
