### ISSUE TITLE
AuthInstance Signout not working

### ISSUE THREAD

**Issue by Toastgeraet** [gsuitedevs/browser-samples#14]
The function handleSignoutClick does not work. A possible fix is the following function body:

    var auth2 = gapi.auth2.getAuthInstance();   
    auth2.signOut().then(function () {});  
    auth2.disconnect();

**Comment by sqrrrl** [comment]
Unable to reproduce this with the current quick starts, nor are the code changes really necessary. Calling disconnect() does change the behavior, but is different than calling signOut().

 If still an issue, please re-open.
