### ISSUE TITLE
Calendar Quickstart doesn't work

### ISSUE THREAD

**Issue by blacknell** [gsuitedevs/browser-samples#18]
I double checked this and also tried in Firefox and Chrome. I'm getting

`Object
details: "Not a valid origin for the client: http://localhost:8000 has not been whitelisted for client ID xxx_obfuscated_.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and whitelist this origin for your project's client ID."
error: "idpiframe_initialization_failed"`

However, I have added `http://localhost:8000` to the Authorised JavaScript origins field in the OAuth Client Id form.

NB. After saving the Authorised JavaScript origins and re-opening the form field is blank which is disconcerting.

**Comment by blacknell** [comment]
Ok. It was click outside then save that did the trick. Glad it was as simple as that. Thanks

**Comment by Roaders** [comment]
I am still having this issue. I have saved the origins in the client ID configuration page then gone back into the page to ensure it has actually saved properly.

**Comment by ub3rb3457** [comment]
same, i also tried going back in and clicking outside the form before saving, still no dice
