### ISSUE TITLE
Google Calendar API error

### ISSUE THREAD

**Issue by eosurman** [gsuitedevs/browser-samples#20]
When I clicked the 'Authorize' button in the browser, a 400 error popped up, saying that it was an "invalid_request. Permission denied to generate login hint for target domain." I replaced the API key and the Client ID properly, so I'm wondering if there is a problem with my Google Suite or maybe something other than that. Any ideas?

**Comment by erickoledadevrel** [comment]
Were you hosting the page on an IP address? That [appears to be a cause](https://stackoverflow.com/a/36162748/702875) of this error.
