### ISSUE TITLE
Bad request found missing parameter

### ISSUE THREAD

**Issue by poom12452** [gsuitedevs/browser-samples#23]
<img width="1280" alt="screen shot 2561-11-13 at 19 27 19" src="https://user-images.githubusercontent.com/33443826/48413384-26560c80-e77a-11e8-9e4a-8e3609150d99.png">

**Comment by poom12452** [comment]
I think there is something missing as I tried to use the code then the <YOUR_API_KEY> parameter did not send the request as I expected.

**Comment by erickoledadevrel** [comment]
I'm not clear what the exact issue is, can you please clarify the behavior you are seeing? Also, which code sample specifically are your referring to?

**Comment by poom12452** [comment]
Sorry for an unclear issue. I used the code from Javascript browser quickstarts in Google Calendar API [Javascript browser quickstarts in Google Calendar API](https://developers.google.com/calendar/quickstart/js) As I followed through each step from turning on the Google API then, it comes to the Set up the sample part I created the file name index.html as the instruction said and copy and paste the code which the only information I have to change is `var CLIENT_ID = '<YOUR_CLIENT_ID>';
      var API_KEY = '<YOUR_API_KEY>';` right? but it showed up like this.
<img width="339" alt="screen shot 2561-11-14 at 09 31 28" src="https://user-images.githubusercontent.com/33443826/48456647-5ccf6e00-e7f2-11e8-93d3-f21bedc82f0a.png">
<img width="432" alt="screen shot 2561-11-14 at 09 32 47" src="https://user-images.githubusercontent.com/33443826/48456648-5d680480-e7f2-11e8-8a3a-cac299c4d3a9.png">
<img width="1280" alt="screen shot 2561-11-14 at 09 45 06" src="https://user-images.githubusercontent.com/33443826/48456656-63f67c00-e7f2-11e8-9dc2-f98dcf11ca19.png">

**Comment by erickoledadevrel** [comment]
Looking at the Chrome console screenshot, it looks like the request still has the API key set to the placeholder value `<YOUR_API_KEY>`. Can you double check that you replaced this placeholder with a real key?

**Comment by poom12452** [comment]
First of all, I just wanna say that I really appreciate your support. However, I had already doubled check it sir, and the result still the same.

**Comment by erickoledadevrel** [comment]
Can you view the source code of the HTML page and ensure the API_KEY variable is set there? Could you perhaps be editing the wrong file?

**Comment by poom12452** [comment]
Sir, I think my issue was solved but I still have no Idea why. I just only delete all of my api and code and start from the scratch again and it worked I guess. Thank you for your help and support.
<img width="1280" alt="screen shot 2561-11-15 at 17 06 28" src="https://user-images.githubusercontent.com/33443826/48545776-50820880-e8f9-11e8-8730-05dba81a2519.png">
