### ISSUE TITLE
Google Calendar JavaScript sample not working - keyInvalid

### ISSUE THREAD

**Issue by Pastew** [gsuitedevs/browser-samples#24]
In Google Calendar sample for JavaScript I got this error:

`{
  "error": {
    "errors": [
      {
        "domain": "usageLimits",
        "reason": "keyInvalid",
        "message": "Bad Request"
      }
    ],
    "code": 400,
    "message": "Bad Request"
  }
}
`

When I changed this
`apiKey: API_KEY,`
to this:
`apikey: API_KEY,`
it worked.

https://github.com/gsuitedevs/browser-samples/blob/master/calendar/quickstart/index.html#L60

**Comment by erickoledadevrel** [comment]
The original key `apiKey` is correct, and if you use `apikey` (lower-case "k") then the value you pass will be ignored. It so happens that the JavaScript client can work with a client ID alone, hence why it worked when you changed it. It's a best practice to set an API key as well as a client ID however, to protect against certain types of attacks. Please double check that you copied the API key correctly and that it's from the same project as the client ID.

**Comment by Pastew** [comment]
@erickoledadevrel , Thanks for response! You are right, it was my mistake. I put client secret instead of API key.
Thank you for clarification, maybe it would be good to note that JS client can work with client ID only and explain why, just like you did above.

Link do guide: https://developers.google.com/calendar/quickstart/js
