### ISSUE TITLE
Calendar quickstart throwing exception in create-react-app

### ISSUE THREAD

**Issue by emarkchrome** [gsuitedevs/browser-samples#25]
I am trying to adapt the code from the Google Calendar browser [quickstart][1] to work in my React app. Whenever I try to run the gapi.client.init method, it throws this error:

    Refused to display 'https://developers.google.com/static/proxy?usegapi=1&jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.en_US.MDhkA3012xc.O%2Fam%3DQQ%2Frt%3Dj%2Fd%3D1%2Frs%3DAGLTcCM6WmePnR12kdbRAwKb1aCuIQXH1Q%2Fm%3D__features__#parent=http%3A%2F%2Flocalhost%3A3000&rpctoken=1847815717' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

I put all my code below. I made sure to whitelist my origin. I don't know if it has to be something besides http://localhost:3000. Sorry if this is the wrong place to ask about this. Nothing I found on Google worked, and nobody has answered a [question](https://stackoverflow.com/questions/53482682/google-calendar-api-gapi-client-init-in-create-react-app-throws-error) about it I asked on StackOverflow.

    import React, { Component } from 'react';
    import config from '../../config';
    
    class Index extends Component {
      componentDidMount() {
        window.gapi.load('client:auth2', function() {
          window.gapi.client.init({
            apiKey: config.apiKey,
            discoveryDocs: config.discoveryDocs,
            clientId: config.clientId,
            scope: config.scope
          });
        });
      }
      login() {
        console.log('logging in...');
        window.gapi.auth2.getAuthInstance().signIn();
      }
      render() {
        return (
          <div>
            <button type="button" onClick={this.login.bind(this)}>Login with Google</button>
          </div>
        )
      }
    }
    
    export default Index;

  [1]: https://github.com/gsuitedevs/browser-samples/blob/master/calendar/quickstart/index.html

**Comment by grant** [comment]
Please Google `in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

**Comment by emarkchrome** [comment]
@grant I scoured a couple of pages with that query and they either told me to clear my cookies (which didn't work) or that I simply would not be allowed to access the file. Does that mean I'm at a dead end or is there something else I'm doing wrong?

P.S. I would have googled the error before posting it here.

**Comment by grant** [comment]
I'm not sure exactly what the problem is here.
We use GitHub to track issues with our current samples in the repo. As this isn't a sample we have, it's best to post on StackOverflow to debug the issue. It seems like a CORS issue, but I could be mistaken.

**Comment by emarkchrome** [comment]
I know, and I posted it there as well. I figured out what the problem was: I didn't include a callback function (even if it's empty) with the gapi.client.init() method. When I added one it worked perfectly.
