### ISSUE TITLE
Issues with Verification

### ISSUE THREAD

**Issue by Jonathanko52** [gsuitedevs/browser-samples#29]
## Expected Behavior

Oauth sign in screen to pop up, ask for permission to access sheets.
(Include the sample name)
Spreadsheet quickstart for Javascript/Browser

## Actual Behavior
Oauth screen pops up. When I click on my e-mail, screen pops up saying 'This app isn't verified.' Rest of app fails to run,

## JavaScript Console Output
No errors.
(View your JavaScript Console to see if there are any errors)

## Specifications

Chrome Browser
Mac OS
Visual Studio Code
HTML page, rendered with webpack.(Intention is to create a React app that uses sheets)

- Browser (Chrome/Internet Explorer/Firefox):
- OS (Mac/Linux/Windows):

**Comment by erickoledadevrel** [comment]
The OAuth consent screen that is presented may show the warning "This app isn't verified" if it is requesting scopes that provide access to sensitive user data. These applications must eventually go through the [verification process](https://support.google.com/cloud/answer/7454865) to remove that warning and other limitations. During the development phase you can continue past this warning by clicking **Advanced > Go to {Project Name} (unsafe)**.

**Comment by erickoledadevrel** [comment]
We've added a note to the Troubleshooting section of the page that mentions how to handle this case: https://developers.google.com/sheets/api/quickstart/js#troubleshooting
