### ISSUE TITLE
Syntax error: gapi.load('client:auth2, initClient);

### ISSUE THREAD

**Issue by jmm0979** [gsuitedevs/browser-samples#30]
I am new to setting up Google App Script API and trying out the sample code but I came across this error below. Please help and advise on how to resolve this. Thank you! 

## Expected Behavior

Able to set up sample using index.html

## Actual Behavior

Syntax error. (line 35, file "index.html")

 _gapi.load('client:auth2', initClient);_

## JavaScript Console Output

Cannot view console output due to error above. 

## Specifications

- Browser (Chrome):
- OS (Mac):

**Comment by erickoledadevrel** [comment]
I'm not able to reproduce this problem. Please check out a fresh copy and try again. It could be that you unintentionally altered some code when pasting in the client ID and API key.
