### ISSUE TITLE
Localhost is not allowed

### ISSUE THREAD

**Issue by IvanAditazz** [gsuitedevs/browser-samples#31]

**Comment by ivangrimaldo** [comment]
Localhost is getting an error: Not a valid origin for the client: http://localhost:8080 has not been whitelisted 

There is not change to configure to run in localhost and is not a first level domain, can you allow the usage in local host to test the features?

**Comment by erickoledadevrel** [comment]
As per the quickstart directions, you need to whitelist this URL in the Cloud console:

https://developers.google.com/sheets/api/quickstart/js

**Comment by Roaders** [comment]
The word whitelist does not appear at all on the page that you link to. 

The error I am getting tells me to whitelist the domain with no indication how. On the google developers console I have added `http://localhost:3000` to the authorised javascript origins list - is that what is meant by whitelisting? If so it didn't work and I am still getting an error.
