### ISSUE TITLE
google calendar JS quickstart error: "domain": "usageLimits", "reason": "keyInvalid", "message": "Bad Request"

### ISSUE THREAD

**Issue by alexandria-lewis** [gsuitedevs/browser-samples#32]
## Expected Behavior

Expected to see no errors because I followed all the instructions from the quickstart
Used the correct OAuth 2.0 client ID and the correct API key, even regenerated the API key to see if a new one would work. It didn't.

## Actual Behavior
Printed this response upon running localhost

Google Calendar API Quickstart

```json
{
  "error": {
    "errors": [
      {
        "domain": "usageLimits",
        "reason": "keyInvalid",
        "message": "Bad Request"
      }
    ],
    "code": 400,
    "message": "Bad Request"
  }
}
```

## JavaScript Console Output

Failed to load resource: the server responded with a status of 400 ()
Failed to load resource: the server responded with a status of 401 ()

## Specifications

- Browser (Chrome/Internet Explorer/Firefox): Chrome
- OS (Mac/Linux/Windows): Mac

**Comment by erickoledadevrel** [comment]
As per the error message, you appear to be using an invalid API key. Please ensure that you pasted your API key into the code as specified and that it doesn't contain any extra whitespace.

**Comment by MessiDaGod** [comment]
> ## Expected Behavior
> Expected to see no errors because I followed all the instructions from the quickstart
> Used the correct OAuth 2.0 client ID and the correct API key, even regenerated the API key to see if a new one would work. It didn't.
> 
> ## Actual Behavior
> Printed this response upon running localhost
> 
> Google Calendar API Quickstart
> 
> ```json
> {
>   "error": {
>     "errors": [
>       {
>         "domain": "usageLimits",
>         "reason": "keyInvalid",
>         "message": "Bad Request"
>       }
>     ],
>     "code": 400,
>     "message": "Bad Request"
>   }
> }
> ```
> 
> ## JavaScript Console Output
> Failed to load resource: the server responded with a status of 400 ()
> Failed to load resource: the server responded with a status of 401 ()
> 
> ## Specifications
> * Browser (Chrome/Internet Explorer/Firefox): Chrome
> * OS (Mac/Linux/Windows): Mac

remove the < and > from the api key and client id

**Comment by ctsstc** [comment]
I was trying the drive example. It seems I had to create an oAuth client ID and an API Key (rather than using the client secret from the oAuth credentials???)
