### ISSUE TITLE
Execute sample for Google Scripts throws 401 error saying unauthorized request

### ISSUE THREAD

**Issue by NotJoHam** [gsuitedevs/browser-samples#34]
## Expected Behavior
I am using the execute method found here to run my Google Script: [Google Script execute](https://github.com/gsuitedevs/browser-samples/blob/13289e1b0488ab432d5559e1b04aea0154f10afb/apps-script/execute/index.js#L18-L75)

It should run the script with no problem

## Actual Behavior

The request throws a 401 error saying "unauthorized request

## JavaScript Console Output

Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.

## Specifications

This is running in a VueJS app. I am not running it from the backend, hence why I am running it with the Javascript API

Windows 10
Chrome Version 73.0.3683.86

**Comment by erickoledadevrel** [comment]
That code requires that sign-in / authorization has already been performed, like what is shown in the quickstart:

https://developers.google.com/apps-script/api/quickstart/js

You'll need to use the same Cloud console project as the script uses, and ensure the scopes match. More information is here: 

https://developers.google.com/apps-script/api/how-tos/execute

**Comment by NotJoHam** [comment]
I have already logged the user in. I have also run gapi.client.init({...}) before I call the script. I can try to run the log in right beforehand and see if that is an issue.

**Comment by erickoledadevrel** [comment]
The error message indicates that an OAuth2 token isn't being sent along with the request, which makes me think the auth is the problem. Check to see that you are successfully signed in and have an auth token before making the request.

**Comment by NotJoHam** [comment]
When I console.log(gapi.auth.getToken()), it returns a token which seems to be legitimate.

**Comment by NotJoHam** [comment]
Okay now I am getting weird behavior, so let me fully explain my issue. I am running my website using VueJS which is a node module. I can't include multiple script tags in my .vue files, so I am including <script src="https://apis.google.com/js/api.js"></script> in my public index.html file. However, I do not have access to a variable name gapi, but I do have access to a variable named google. Also, there is no google.client. Why is this if I am including the same javascript api as shown in the quickstart example?

**Comment by NotJoHam** [comment]
Now I am getting an error when I run:

gapi.client.init({
                apiKey: API_KEY,
                clientId: CLIENT_ID,
                discoveryDocs: DISCOVERY_DOCS,
                scope: SCOPES
              })

The error is a 400 error saying "Request contains an invalid argument."

**Comment by erickoledadevrel** [comment]
You seem to have strayed far from the samples in this repo, and the problem seems more related to the library than anything G Suite. Please try filing an issue on the JavaScript client's repo to see if they can help: https://github.com/google/google-api-javascript-client/issues
