### ISSUE TITLE
After running the code I got only white blank window with above written "Google Sheets API Quickstart"

### ISSUE THREAD

**Issue by mmncoder** [gsuitedevs/browser-samples#36]
## Expected Behavior

`The first time you run the sample, it prompts you to authorize access:

Click the Authorize button to open the authorization window.

If you're not already logged in to your Google account, the window prompts you to log in. If you are logged in to multiple Google accounts, you must select one account to use for the authorization.

Click the Accept button.

(Include the sample name) `

# Actual Behavior
A blank white window with above written  "**_Google Sheets API Quickstart"_**

## JavaScript Console Output
(View your JavaScript Console to see if there are any errors)
`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('file://') does not match the recipient window's origin ('null').`

## Specifications

- Browser (Chrome/Internet Explorer/Firefox): Chrome
- OS (Mac/Linux/Windows): Linux

**Comment by erickoledadevrel** [comment]
Are you hosting the page using the Python server as shown in the quickstart instructions, or are you opening it directly from your file system? AKA, a URL of `file://`.

**Comment by mmncoder** [comment]
> Are you hosting the page using the Python server as shown in the quickstart instructions, or are you opening it directly from your file system? AKA, a URL of `file://`.

Sorry for delay reply. I am using Python server as shown in the quickstart instructions.

**Comment by erickoledadevrel** [comment]
Did you use an existing OAuth2 client ID, or did you create a new one using the button? The error message is not something we've seen before, and I don't know what could be causing it except either not using localhost or using a client ID with a strange configuration.

**Comment by mmncoder** [comment]
> Did you use an existing OAuth2 client ID, or did you create a new one using the button? The error message is not something we've seen before, and I don't know what could be causing it except either not using localhost or using a client ID with a strange configuration.

I am deeply sorry being late to reply again. Last Monday I have started my new job and for this I had to be at office from morning till evening and being busy with understanding the project which I am going do in the job. That's why I couldn't manage time to sit with this issue. As the issue was around 3 weeks ago and after having the issue, I moved from that project, right now I can't remember about the environment where these issue was raised. And now I have very limited time sit with the project and fine the details.
So if you would not mind, then I will try sit with this project where I had the issue as soon as I will find some time and come back to you. 
Thanks!

**Comment by erickoledadevrel** [comment]
No worries. I'll close this issue for now, but if you find more information please add a comment and I'll reopen it.

**Comment by eferris** [comment]
Same thing here ... blank page with the msg Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('file://') does not match the recipient window's origin ('null') in the Console.  I am unclear how to load the page on the python server and suspect that is related....  I used the file system (MacOS). Any help appreciated.
