### ISSUE TITLE
Sheets Quickstart example doesn't work (unlike #16 and #36)

### ISSUE THREAD

**Issue by icedwater** [gsuitedevs/browser-samples#40]
## Expected Behavior
When running the Google Sheets v4 API [JavaScript Quickstart][js], the **Authorize** button should appear below the Quickstart text.

This was [reported 2 years ago][so] with no success on StackOverflow.

## Actual Behavior

Only the text "Quickstart" appears.

## JavaScript Console Output

    client_id and scope must both be provided to initialize OAuth.   cb=gapi.loaded_0:84

## Specifications

- Browser: Chromium 73.0.3683.86
- OS: Linux, Ubuntu 16.04

[js]: https://developers.google.com/sheets/api/quickstart/js
[so]: https://stackoverflow.com/questions/43830848

**Comment by erickoledadevrel** [comment]
Are you replacing the client ID placeholder as described in the instructions?

> Replace the placeholder <YOUR_CLIENT_ID> in the copied code with the client ID you created in Step 1. Likewise, replace the placeholder <YOUR_API_KEY> with the API key you created.

**Comment by icedwater** [comment]
Yes, thanks for checking.

**Comment by erickoledadevrel** [comment]
I tried to replicate the problem, but the code worked perfectly after pasting in those two keys. Let me know if you find other clues to help me troubleshoot.

**Comment by icedwater** [comment]
All I have is this other error message which I didn't paste as I couldn't make sense of it. It occurs on `cb=gapi.loaded_0:116`: 

    Uncaught TypeError: Cannot read property 'isSignedIn' of null
        at (index):35
        at h.r2 (cb=gapi.loaded_0:125)
        at xs (cb=gapi.loaded_0:128)
        at Wq (cb=gapi.loaded_0:128)
        at _.C.uea (cb=gapi.loaded_0:128)
        at Ap (cb=gapi.loaded_0:120)

I've tried regenerating keys and ID instead of using the ones from 2 years prior, thinking they had somehow expired, but it did not work.

**Comment by erickoledadevrel** [comment]
Is this error occurring on page load, or after clicking the sign-in button?

**Comment by erickoledadevrel** [comment]
Have you tried loading the page in incognito mode? Perhaps some extension you have installed is messing up the sign-in flow?

**Comment by icedwater** [comment]
I run in Incognito by default. There is no sign-in button to click, hence "Only the text /Quickstart/ appears."

**Comment by erickoledadevrel** [comment]
I apologize for the delay. Unfortunately I still haven't been able to replicate the issue or narrow it down. I'm going to close this for now, but hopefully we'll find a clue in the future.
