### ISSUE TITLE
People Quickstart Broken for Chrome

### ISSUE THREAD

**Issue by clintonb** [gsuitedevs/browser-samples#59]
## Expected Behavior
I expect to click the Authorize button, select my account, and view a list of contacts.

https://github.com/gsuitedevs/browser-samples/blob/master/people/quickstart/index.html

## Actual Behavior
I authorize, and nothing happens _in Chrome_. The quickstart works as expected in Firefox.

## JavaScript Console Output
There are no errors, just a cookie warning:

```
A cookie associated with a cross-site resource at <URL> was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at <URL> and <URL>.
```
All of the cookies are on the `google.com` domain. 

## Specifications

- Browser (Chrome/Internet Explorer/Firefox): Chrome 79.0.3945.88
- OS (Mac/Linux/Windows): macOS 10.14.6

It's a bit ironic that a Google quickstart does not work with Google Chrome. It would be great if this quickstart just worked, or the troubleshooting section at https://developers.google.com/people/quickstart/js#troubleshooting mentions this issue.

**Comment by grant** [comment]
I believe this issue is the same one reported here:
https://github.com/google/google-api-javascript-client/issues/561

**Comment by clintonb** [comment]
Yes. Same issue. Thanks.
