### ISSUE TITLE
Gmail API quickstart missing API key variable

### ISSUE THREAD

**Issue by Penguinlay** [gsuitedevs/browser-samples#7]
Hi, I am following [this guide](https://developers.google.com/gmail/api/quickstart/js#step_1_turn_on_the_api_name) from Google Developers... 

According to the direction, I were to replace the placeholder `<YOUR_API_KEY>` with my own API key. But, in `index.html`, that variable is not available. I continued through the sample instructions, and it works fine without that step. However, this is my first time, so I am not sure if the instruction or the code is wrong. And, I don't know the repo for that quickstart documentation either. So, I just started the issue here.

**Comment by erickoledadevrel** [comment]
Thanks for the bug report!
